### ISSUE TITLE
 Issue with the zoom dropdown

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/svgedit#35]
![image](https://user-images.githubusercontent.com/20402845/103831921-6e80c900-507d-11eb-95ed-3333a8ec8de7.png)

**Comment by AgriyaDev5** [comment]
![Screenshot at 2021-01-08 21:53:12](https://user-images.githubusercontent.com/44435283/104039100-f096fc00-51fb-11eb-8bf2-bc25d7264bd0.png)

please check above screen shot. my end this drop down load properly. Let me know your feedback ?

**Comment by jfhenon** [comment]
Strange. I tested again and it was broken.
