### ISSUE TITLE
 look of opacity button should like the zoom button (without the dropdown button)

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/svgedit#36]
![image](https://user-images.githubusercontent.com/20402845/103832038-ad168380-507d-11eb-9390-4c5e7c23f84d.png)

**Comment by AgriyaDev5** [comment]
PR: https://github.com/OptimistikSAS/svgedit/pull/54/files

**Comment by jfhenon** [comment]
I approved it and merged it after a quick check. I will close the issue after doing more tests later tonight.
