### ISSUE TITLE
opacity button/stroke size/radius button don’t allow the 0 value (it is 0 in the box but not reflected on the element). This seems to be an issue with the component itself.

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/svgedit#39]
![image](https://user-images.githubusercontent.com/20402845/103832299-3cbc3200-507e-11eb-9c05-17464624c88f.png)

**Comment by AgriyaDev5** [comment]
PR: https://github.com/OptimistikSAS/svgedit/pull/60
