### ISSUE TITLE
The stroke style dropdown is not correct (look and behavior)

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/svgedit#40]
![image](https://user-images.githubusercontent.com/20402845/103832400-7db44680-507e-11eb-8ad2-bf9db319a049.png)

**Comment by AgriyaDev5** [comment]
Current stroke drop down style screen shot given below. please check it and please give your feedback. 


![Screenshot at 2021-02-22 10:30:37](https://user-images.githubusercontent.com/44435283/108664584-13097e00-74f9-11eb-9024-36a1910a6b3b.png)

**Comment by jfhenon** [comment]
The contrast is not good. The background should be clearer or the text should be white
Also the button height needs to be consistent with the fields before.
