### ISSUE TITLE
With a small window, the look of the top toolbar is broken (especially with  a text element)

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/svgedit#43]
![image](https://user-images.githubusercontent.com/20402845/103833021-23b48080-5080-11eb-847a-7b9dd9b51bd6.png)

**Comment by AgriyaDev5** [comment]
PR: https://github.com/OptimistikSAS/svgedit/pull/75

**Comment by AgriyaDev5** [comment]
![screenshot-localhost_8000-2021 02 22-19_50_20](https://user-images.githubusercontent.com/44435283/108721399-f6e0fd80-7547-11eb-8f53-ff598d930e62.png)

![screenshot-localhost_8000-2021 02 22-19_50_49](https://user-images.githubusercontent.com/44435283/108721393-f5173a00-7547-11eb-884f-29584f9929f6.png)
![Screenshot at 2021-02-22 20:03:02](https://user-images.githubusercontent.com/44435283/108722312-06147b00-7549-11eb-8251-44122491b05e.png)
