### ISSUE TITLE
Move this jQuery component to a web component (ie. get rid of jquery graduate and picker components)

### ISSUE THREAD

**Issue by jfhenon** [OptimistikSAS/svgedit#46]
![image](https://user-images.githubusercontent.com/20402845/103833655-cae5e780-5081-11eb-900f-91811acd11d6.png)
![image](https://user-images.githubusercontent.com/20402845/103833746-084a7500-5082-11eb-8caf-acc9d198117d.png)

**Comment by AgriyaDev5** [comment]
PR: https://github.com/OptimistikSAS/svgedit/pull/73
